"""test

Revision ID: 090625219dc2
Revises: 
Create Date: 2025-09-14 07:43:24.893674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090625219dc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # add column as nullable first to avoid failures if existing rows are present
    op.add_column('documents', sa.Column('user_id', sa.Integer(), nullable=True))
    # create a named foreign key constraint
    op.create_foreign_key('fk_documents_user_id_users', 'documents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_user_id_users', 'documents', type_='foreignkey')
    op.drop_column('documents', 'user_id')
    # ### end Alembic commands ###
